[package]
name = "sf-net"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
serde.workspace = true
chrono = { workspace = true, features = ["serde"] }
sha2.workspace = true
thiserror.workspace = true
zip.workspace = true
md-5 = "0.10.6"
hmac = "0.12.1"
